### ISSUE TITLE
Hate speech restrictions is at odds with human rights declaration

### ISSUE THREAD

**Issue by chrisjensen** [raisely/jwl#10]
"Universal access to human rights" would likely be interpreted by the Universal Declaration. [Article 19](https://en.wikisource.org/wiki/Universal_Declaration_of_Human_Rights#Article_19) of the declaration is at odds with the restrictions on hate speech in paragraph 4a.

**Comment by tommaitland** [comment]
I disagree with this one, the articles of the UDHR don't stand alone and there's other articles in the declaration protecting against the harm caused by hate speech (20 & 27). It seems like the HRC has taken an interpretation in the past of where hate speech has caused a tangible harm, it doesn't fall under Article 19. (http://www.law-democracy.org/wp-content/uploads/2010/07/10.02.hate-speech.Macedonia-book.pdf)
